#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

exec s6-setuidgid hotio python "${APP_DIR}/Tautulli.py" --nolaunch --config "${CONFIG_DIR}/app/config.ini" --datadir "${CONFIG_DIR}/app"
