#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

redirect_cmd() {
    if [[ "${DEBUG}" == "yes" ]]; then
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}

redirect_cmd exec s6-setuidgid hotio python "${APP_DIR}/Tautulli.py" --nolaunch --config "${CONFIG_DIR}/app/config.ini" --datadir "${CONFIG_DIR}/app"
