#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

exec s6-setuidgid hotio python3 "${APP_DIR}/Tautulli.py" --nolaunch --config "${CONFIG_DIR}/config.ini" --datadir "${CONFIG_DIR}"
